keys:
  - &alexbn age1xlf3s6yzu6a67ha3vqrcy75s89fg85rw9fcspfgh93sm8ptx294qlv722x
  - &dev-vm age1pxxe5nsezvwawrd4wdweanuxjfg8as8ct0cv6lsyzt7y454ks46s9asvv7
  - &agent-vm age164sxumnzs9f4p8c3qk7x2rgsug0ptemrpy73vx0nmny8l2tfevjqu53jea
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *alexbn
          - *dev-vm
          - *agent-vm
